# Generated by Django 3.2.3 on 2021-08-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/defaults.jpg', upload_to='images/'),
        ),
    ]
